import {type BlogVirConfig} from 'blog-vir';

const blogVirConfig = {
    rssFeed: {
        siteUrl: 'https://electrovir.github.io/blog-vir/demo/',
        title: 'blog-vir example',
        description: 'An example blog generated by blog-vir.',
    },
} satisfies BlogVirConfig;

export default blogVirConfig;
